//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATP.Infrastructure.Localization.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Level.
        /// </summary>
        internal static string AddLevel {
            get {
                return ResourceManager.GetString("AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseShell {
            get {
                return ResourceManager.GetString("CloseShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Strategy.
        /// </summary>
        internal static string LoadStrategy {
            get {
                return ResourceManager.GetString("LoadStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVELS.
        /// </summary>
        internal static string MainLevelsNode {
            get {
                return ResourceManager.GetString("MainLevelsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATIONS.
        /// </summary>
        internal static string MainNode {
            get {
                return ResourceManager.GetString("MainNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Level.
        /// </summary>
        internal static string NewLevelName {
            get {
                return ResourceManager.GetString("NewLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operations loaded.
        /// </summary>
        internal static string NoOperationsLoaded {
            get {
                return ResourceManager.GetString("NoOperationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Levels.
        /// </summary>
        internal static string OpenLevels {
            get {
                return ResourceManager.GetString("OpenLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string OpenOperationsLib {
            get {
                return ResourceManager.GetString("OpenOperationsLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part File.
        /// </summary>
        internal static string OpenPartFile {
            get {
                return ResourceManager.GetString("OpenPartFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operations loaded.
        /// </summary>
        internal static string OperationsLoaded {
            get {
                return ResourceManager.GetString("OperationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Operations Library.
        /// </summary>
        internal static string PromptForOperationsLibrary {
            get {
                return ResourceManager.GetString("PromptForOperationsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Level.
        /// </summary>
        internal static string RemoveLevel {
            get {
                return ResourceManager.GetString("RemoveLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string RunScan {
            get {
                return ResourceManager.GetString("RunScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Levels.
        /// </summary>
        internal static string SaveLevels {
            get {
                return ResourceManager.GetString("SaveLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Strategy.
        /// </summary>
        internal static string SaveStrategy {
            get {
                return ResourceManager.GetString("SaveStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy has been saved.
        /// </summary>
        internal static string StrategySaved {
            get {
                return ResourceManager.GetString("StrategySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy Designer.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
    }
}
